# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Diego/Desktop/Proyecto-1-SEP/conectar_proyecto/conectar_proyecto.srcs/sources_1/bd/design_1/ip/design_1_sistema_morse_0_0/design_1_sistema_morse_0_0.xci
# IP: The module: 'design_1_sistema_morse_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Desktop/Proyecto-1-SEP/conectar_proyecto/conectar_proyecto.srcs/sources_1/bd/design_1/ip/design_1_sistema_morse_0_0/constrs_1/imports/archivos_vivado/Zybo-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sistema_morse_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Diego/Desktop/Proyecto-1-SEP/conectar_proyecto/conectar_proyecto.srcs/sources_1/bd/design_1/ip/design_1_sistema_morse_0_0/design_1_sistema_morse_0_0.xci
# IP: The module: 'design_1_sistema_morse_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Desktop/Proyecto-1-SEP/conectar_proyecto/conectar_proyecto.srcs/sources_1/bd/design_1/ip/design_1_sistema_morse_0_0/constrs_1/imports/archivos_vivado/Zybo-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sistema_morse_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
